apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "master"
jobs:
  Checkout:
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1
       
        
  Build:
    steps:
      - name: Set up Java
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
         
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Build
        uses: docker://alpine/git:latest
        image: adoptopenjdk:17-jdk-hotspot
        run: |
           
           chmod +x ./gradlew
           ./gradlew build
    needs: Checkout
    
